### ISSUE TITLE
Support for Excel files

### ISSUE THREAD

**Issue by darshilparmar** [prioritythinking/Report-Generator#8]
Hi,
Is there any way we could make this system to support excel?
If I want to contribute to this how can I do that?
What are the languages and things I should know?

**Comment by prioritythinking** [comment]
Hello. All this project requires is C#.

The key package that was downloaded through NuGet is Microsoft.Office.Interop.Word. I have to imagine that there is a Microsoft.Office.Interop.Excel package that has all the same functionality of copying/pasting and scanning through the document that the process requires.

Not sure this qualifies as an "issue" so I will close this thread and please contact me directly with any further questions. Thank you.
